In [ ]:
# importing libraries
# !pip install tensorflow

In [ ]:
from typing_extensions import TypeForm
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")


#  Loading the data

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/bhabani0807/Data-sets/refs/heads/main/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


load the data

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# **Data transformation**

In [ ]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'])
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,True,False,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,True,False,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,True,False,False,True,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,False,True,False,False,True


# **Model Building**

In [ ]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [ ]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6245 - loss: 0.6772
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6323 - loss: 0.6703
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6349 - loss: 0.6715
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6335 - loss: 0.6693
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6350 - loss: 0.6683
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6434 - loss: 0.6588
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6362 - loss: 0.6685
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6344 - loss: 0.6723
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6461 - loss: 0.6657
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6399 - loss: 0.6614
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6462 - loss: 0.6600
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
ypred = ann.predict(xtest)
ypred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.15017541],
       [0.35889232],
       [0.06145074],
       ...,
       [0.4233703 ],
       [0.40390152],
       [0.47451472]], dtype=float32)

In [ ]:
ytest

,Exited
9953,0
3850,0
4962,0
3886,0
5437,0
...,...
3919,0
162,0
7903,0
2242,0


In [ ]:
ypred > 0.05

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ypred = ypred > 0.05
ypred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ytest

,Exited
9953,0
3850,0
4962,0
3886,0
5437,0
...,...
3919,0
162,0
7903,0
2242,0


In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.50      0.00      0.00      1585
           1       0.21      0.99      0.34       415

    accuracy                           0.21      2000
   macro avg       0.35      0.50      0.17      2000
weighted avg       0.44      0.21      0.07      2000



# **Hyper parameter tuning**

In [ ]:
#! pip install keras-tuner

In [ ]:
import keras_tuner as kt

In [ ]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [ ]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [ ]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8180000185966492

Best val_accuracy So Far: 0.8180000185966492
Total elapsed time: 00h 00m 09s


In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8128 - loss: 0.4182 - val_accuracy: 0.8250 - val_loss: 0.4026
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8187 - loss: 0.4093 - val_accuracy: 0.8335 - val_loss: 0.3931
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8329 - loss: 0.3976 - val_accuracy: 0.8370 - val_loss: 0.3831
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8301 - loss: 0.3975 - val_accuracy: 0.8435 - val_loss: 0.3756
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8449 - loss: 0.3693 - val_accuracy: 0.8470 - val_loss: 0.3688
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8441 - loss: 0.3721 - val_accuracy: 0.8460 - val_loss: 0.3640
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8468 - loss: 0.3751 - val_accuracy: 0.8485 - val_loss: 0.3607
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8506 - loss: 0.3657 - val_accu

In [ ]:
model.evaluate(xtrain,ytrain)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8656 - loss: 0.3381


[0.3361148238182068, 0.8622499704360962]

# **Regression**

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Regression.csv")
df

,price,feature1,feature2
0,461.527929,999.787558,999.766096
1,548.130012,998.861615,1001.042403
2,410.297162,1000.070267,998.844015
3,540.382220,999.952251,1000.440940
4,546.024553,1000.446011,1000.338531
...,...,...,...
995,476.526078,1000.018988,999.672732
996,457.313186,998.855379,1000.020026
997,456.720993,1001.451646,998.847605
998,403.315576,1000.771023,998.562851


In [ ]:
x = df.iloc[:,1:]
y = df["price"]

In [ ]:
x= sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2, random_state =1)

In [ ]:
ann = Sequential()

ann.add(Dense(units = 30, activation="relu"))
ann.add(Dense(units = 20, activation="relu"))

ann.add(Dense(units = 1))

ann.compile(optimizer = 'adam', loss = 'mse')

ann.fit(xtrain,ytrain, epochs= 100 , validation_data= (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 251061.5000 - val_loss: 262321.5312
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 254746.5469 - val_loss: 261536.5625
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 254483.4844 - val_loss: 260266.8438
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 252426.7969 - val_loss: 258239.6875
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 256230.6719 - val_loss: 255140.9375
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 251342.3750 - val_loss: 250777.0469
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 247121.0156 - val_loss: 244774.8594
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 235057.7344 - val_loss: 236990.0000
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 230078.8125 - val_loss: 227171.0781
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 214372.4219 - val_loss: 215292.1250
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/st

In [ ]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[475.26416],
       [527.2868 ],
       [495.44736],
       [536.90753],
       [657.6441 ],
       [344.59042],
       [353.5262 ],
       [374.1319 ],
       [722.6486 ],
       [501.4367 ],
       [477.83337],
       [508.04617],
       [495.8791 ],
       [372.79373],
       [549.9001 ],
       [489.6712 ],
       [578.107  ],
       [550.8205 ],
       [482.6478 ],
       [498.7089 ],
       [467.2224 ],
       [603.89746],
       [438.85587],
       [579.9884 ],
       [423.64746],
       [522.5955 ],
       [384.80753],
       [497.71814],
       [544.15515],
       [351.19684],
       [438.10104],
       [642.66583],
       [561.5337 ],
       [538.6183 ],
       [612.2675 ],
       [550.5455 ],
       [405.82   ],
       [575.973  ],
       [557.9389 ],
       [521.0002 ],
       [420.24152],
       [737.71625],
       [525.62744],
       [532.5995 ],
       [515.89685],
       [451.11887],
       [526.7655 ],
       [525.20605],
       [590.4198 ],
       [466.00934],


In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,yp)

0.9666495459060533